name: setup-node

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v5
      with:
        node-version-file: .tool-versions
        cache: npm
        cache-dependency-path: package-lock.json
    - run: npm ci
      shell: bash
