name: cron

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
  # NOMERGE
  push:
    branches:
      - feat/allow-community-providers

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-terraform
      - run: npm run generate
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'chore(cron): update'
